# version: "3.8"
name: logitrackpro-dev
services:
  postgresql:
    image: postgres:16.3
    ports:
      - "5432:5432"
    env_file:
      - envs/.env.postgres
    networks:
      - logitrackpro
    restart: unless-stopped
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - envs/.env.api
    restart: unless-stopped
    networks:
      - logitrackpro
    depends_on:
      - postgresql

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - envs/.env.web
    restart: unless-stopped
    networks:
      - logitrackpro
    depends_on:
      - api

volumes:
  postgresql-data:

networks:
  logitrackpro:
    driver: bridge
